#!/bin/bash

set -e

function normalize() {
    echo $( cd "$1" && pwd )
}

scripts_directory=$(normalize $(dirname "${BASH_SOURCE[0]}"))
root_directory=$(normalize "$scripts_directory/..")
source_directory=$(normalize "$root_directory/source")
build_directory="$root_directory/build"

if [[ -e "$build_directory" ]]; then
    echo "Removing '$build_directory'..."
    rm -r "$build_directory"
fi

echo "Creating '$build_directory'..."
mkdir -p "$build_directory"

pushd "$root_directory" > /dev/null
cp -R "$source_directory" "$build_directory/InJapan.wdgt"
popd > /dev/null
